### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_MMA8452Q_Arduino_Library#5] opened 2016-08-20 21:36 UTC
In two places in the source code is a Wire.requestFrom() followed by a while-loop to wait for data. That while-loop is not needed. 
The Wire.requestFrom() returns after the I2C transaction has completely finished, and the data is in the receive buffer of the Wire library.

If there was an error on the I2C bus and Wire.requestFrom() returns with no data, that while-loop will halt the sketch.

**Comment by savetheclocktower** [comment] 2016-12-09 23:15
Yep, pretty sure I just got bitten by this. Couldn't figure out why my sketch wouldn't stay running for more than a few hours at most. I think it was hanging the first time it got an unexpected I2C result. Thanks, @Koepel! Your suggestion seems to have fixed it.

**Comment by Koepel** [comment] 2016-12-09 23:24
You should check your I2C bus. For example different voltage levels, cable length, and so on. The I2C bus is not fault-tolerant. 
The issue that I mentioned is about how to use the Arduino Wire library, it is not a big bug. The Wire library itself could also halt a sketch (when SDA or SCL is shortcut to GND or to each other). That means that your I2C hardware bus must be okay.

**Comment by savetheclocktower** [comment] 2016-12-09 23:32
So I've got an ESP8266 hooked up to two MMA8452Qs. I could reproduce the hang simply by unplugging one of the accelerometers, or even shaking the wire harness a little bit. I improved my strain relief, but that only helped a bit.

Once I commented out the `while` loops, I was able to unplug either (or both) sensors and have the sketch continue to run. When I get time I'll look at the serial monitor to figure out exactly how the sketch behaves when it doesn't get a new reading from the sensor, but if all that happens is that it uses the last values written, that's fine.

I don't have much experience at low-level programming, so any lesson learned is progress. I was thinking I'd have to ditch this library and use Wire directly, but it looks like that may not be necessary.

**Comment by Koepel** [comment] 2016-12-10 09:04
I think the ESP8266 Wire library is a software implementation. If I remember it well, it is not fully compatible with the Arduino Wire library, and certainly not compatible when the Wire library is used in a wrong way. You could have a combination of three things: (1) The ESP8266 Wire implementation. (2) The hardware I2C bus. (3) The unnecessary while-loop in this library.

**Comment by nseidle** [comment] 2018-03-22 16:57
The original issue was fixed awhile ago. Closing out.

**Closed as completed by nseidle** 2018-03-22 16:57 UTC
